server:
  port: 8089
ali:
  log-hub:
    accounts:
      - accessId: [your accessId here]
        accessKey: [your accessKey here]
        projects:
          - project: charleslzqsample
            endpoint: http://cn-hangzhou.log.aliyuncs.com
